A large update full of exciting testing stuff

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,13 +1,14 @@
-#!/bin/sh
+#!/bin/bash
 ##
 # A quick/simple script to get masterless salt deployed and configured.
 # See help text (./bootstrap -h) and README.rst for requirements.
 #
 # skeys.gpg, generated with:
-#   cd /etc/salt; tar -cf- gpgkeys | gpg --symmetric --cipher-algo TWOFISH -o skeys.gpg
+#   gpg --homedir /etc/salt/gpgkeys --export-secret-keys --export-options export-backup <KEY-ID> \
+#       | gpg --symmetric --cipher-algo TWOFISH -o skeys.gpg
 #
-# TEST_MODE: This script will behave different if the $TEST_MODE environment
-#            variable is set. This is meant for (insecure) automated testing.
+# BS_*: This script will dump all "BS_*" environment variables into a configuration
+#       file for salt-minion; this provides a way to mangle saltsolo.conf.
 ##
 
 main() {
@@ -19,10 +20,13 @@ main() {
 	mkdir -p /etc/salt/minion.d
 
 	# Install Masterless Salt
-	install_dependencies || die 'Failed to install dependencies'
+	configure_apt || die 'Failed to configure apt'
+	apt-get -y install gpg python3-pygit2 wget || die 'Failed to install dependencies'
 	configure_minion || die 'Failed to install salt-minion'
 	deploy_gpgkeys || die 'Failed to unpack GPG keys'
-	apt-get install -y salt-minion || die 'Failed to install salt-minion'
+	#TODO: This is TEMPORARY hack because we need >= 3004.0
+	apt-get install -y salt-minion=3004.1+dfsg-2 salt-common=3004.1+dfsg-2 || die 'Failed to install salt-minion'
+	#apt-get install -y salt-minion || die 'Failed to install salt-minion'
 
 	# Run Highstate and Configure System
 	run_highstate || die 'Provisioning process (highstate) failed'
@@ -41,33 +45,34 @@ show_usage() {
 	Options:
 	  -k [http]${t}Location of encrypted blob containing Salt GPG keys (can be file)
 	  -p [path]${t}File with password used to decrypt gpg blob
+	  -l X${t}Log level (0=Debug, 1=Info, 2=Warn, 3=Error)
 	  -h${t}${t}Print this help text
 
-	Defaults (Environment Variables):
+	Environment Variables (Defaults):
 	  TH_SALTGPG${t}https://raw.githubusercontent.com/MTecknology/teckhost/master/pillar/skeys.gpg
 	  TH_SALTPWF${t}/tmp/gpgpassphrase
+	  LOG_LEVEL${t}1  (info)
+	  keydir${t}/etc/salt/gpgkeys
+	  BS_*${t}${t}<none>
 	EOF
 }
 
 # Parse options, prioritizing args > env > defaults
-# Exports: TH_SALTGPG
 parse_options() {
 	# Default values
 	# These can be overridden by setting environment variables
-	if [ -n "$TEST_MODE" ]; then
-		export TH_SALTGPG="${TH_SALTGPG:-https://raw.githubusercontent.com/MTecknology/teckhost/master/test/pillar/skeys.gpg}"
-	else
-		export TH_SALTGPG="${TH_SALTGPG:-https://raw.githubusercontent.com/MTecknology/teckhost/master/pillar/skeys.gpg}"
-	fi
+	export TH_SALTGPG="${TH_SALTGPG:-https://raw.githubusercontent.com/MTecknology/teckhost/master/pillar/skeys.gpg}"
 	export TH_SALTPWF="${TH_SALTPWF:-/tmp/gpgpassphrase}"
+	export LOG_LEVEL="${LOG_LEVEL:-1}"
 
 	# Modify defaults
-	while getopts 'k:p:h' opt; do
+	while getopts 'k:p:l:h' opt; do
 		case "$opt" in
-			(k) TH_SALTGPG="$OPTARG";;
-			(p) TH_SALTPWF="$OPTARG";;
-			(h) show_usage; exit 0;;
-			(*) die "Invalid option: $opt"
+			k) TH_SALTGPG="$OPTARG";;
+			p) TH_SALTPWF="$OPTARG";;
+			l) LOG_LEVEL="$OPTARG";;
+			h) show_usage; exit 0;;
+			*) die "Unexpected argument provided: '$OPT'";;
 		esac
 	done
 }
@@ -77,13 +82,13 @@ safety_checks() {
 	command_present apt-get || die 'Must have apt-get available'
 }
 
-# Install dependencies to deploy gpg keys and run salt
-# NOTE: This also wipes /etc/apt/sources.list to ensure clean sources
-install_dependencies() {
+# Ensure a clean apt state prior to salt management
+configure_apt() {
+	# Find $OSCODENAME
 	# Seems excessive when only one path is likely, but who knows how this might get used
-	if [ -n "$OSCODENAME" ]; then
-		: # do nothing if a value was already set
-	elif [ -f /etc/os-release ]; then
+	if [[ -n "$OSCODENAME" ]]; then
+		log "$DEBUG" "Found \$OSCODENAME=$OSCODENAME in environment"
+	elif [[ -f /etc/os-release ]]; then
 		# most likely path
 		. /etc/os-release
 		OSCODENAME="$VERSION_CODENAME"
@@ -92,22 +97,40 @@ install_dependencies() {
 	else
 		die 'Could not figure out OSCODENAME'
 	fi
+
 	# Force a pristine/known-good apt configuration
-	rm -rf /etc/apt/sources.*
+	rm -rf /etc/apt/sources.list*
+	mkdir /etc/apt/sources.list.d
 	cat >/etc/apt/sources.list <<-EOF
 		deb http://deb.debian.org/debian $OSCODENAME main contrib non-free
 		deb http://security.debian.org/debian-security $OSCODENAME-security main contrib non-free
 		deb http://deb.debian.org/debian $OSCODENAME-updates main contrib non-free
+
+		# Newer Packages (use with extreme caution)
+		deb http://deb.debian.org/debian testing main non-free contrib
+		deb http://deb.debian.org/debian sid main non-free contrib
+		EOF
+	cat >/etc/apt/preferences.d/pinning <<-EOF
+		Package: *
+		Pin: release n=bullseye
+		Pin-Priority: 900
+
+		Package: *
+		Pin: release n=testing
+		Pin-Priority: 800
+
+		Package: *
+		Pin: release n=sid
+		Pin-Priority: 700
 		EOF
 	apt-get update
-	apt-get -y install gpg python3-pygit2 wget
 }
 
 # Run a highstate
 run_highstate() {
 	# This is an ugly hack because of some networking hiccups during some deployments.
 	if ! salt-call --local -l debug state.highstate; then
-		echo 'FIRST HIGHSTATE FAILED; Sleeping a few minutes before retrying.'
+		log "$WARN" 'FIRST HIGHSTATE FAILED; Sleeping a few minutes before retrying.'
 		sleep 240
 		salt-call --local -l debug state.highstate
 	fi
@@ -115,20 +138,29 @@ run_highstate() {
 
 # Create default minion configuration
 configure_minion() {
-	testdir=''; [ -n "$TEST_MODE" ] && testdir='test/'
+	# Copy BS_* env vars to grains file
+	# Provides persistence for information that is likely coming from grub for testing.
+	for var in "${!BS_@}"; do
+		log "$DEBUG" "Saving bootstrap var(${var#BS_}): ${!var}"
+		[ ! -f '/etc/salt/minion.d/bootstrap.conf' ] &&
+			echo -e 'grains:\n  bootstrap:' >/etc/salt/minion.d/bootstrap.conf
+		echo "    ${var#BS_}: ${!var}" >>/etc/salt/minion.d/bootstrap.conf
+	done
+
+	# Write temporary config file; Salt will overwrite using (bootstrap.conf) grains.
 	cat >/etc/salt/minion.d/saltsolo.conf <<-EOF
 		file_client: local
 		fileserver_backend:
 		  - gitfs
 		gitfs_remotes:
-		  - https://github.com/MTecknology/teckhost.git:
-		    - root: states
+		  - ${BS_gitrepo:-https://github.com/MTecknology/teckhost.git}:
+		    - root: ${BS_states_root:-states}
 		ext_pillar:
 		  - git:
-		    - https://github.com/MTecknology/teckhost.git:
-		      - root: ${testdir}pillar
+		    - ${BS_gitrepo:-https://github.com/MTecknology/teckhost.git}:
+		      - root: ${BS_pillar_root:-pillar}
 		EOF
-		# NOTE: Salt will overwrite this if the hostname is wrong.
+		# NOTE: Salt will overwrite this, verify bootstrap (BS) grains are written.
 }
 
 # Download and unpack Salt GPG keys
@@ -136,29 +168,37 @@ configure_minion() {
 deploy_gpgkeys() {
 	# Get the encrypted keys
 	gpgblob="$(mktemp)"
-	if [ -f "$TH_SALTGPG" ]; then
+	keydir="${keydir:-/etc/salt/gpgkeys}"
+	if [[ -f "$TH_SALTGPG" ]]; then
+		log "$DEBUG" "Copying GPG blob from $TH_SALTGPG"
 		cp "$TH_SALTGPG" "$gpgblob" || return 1
 	else
+		log "$DEBUG" "Downloading GPG blob from $TH_SALTGPG"
 		wget "$TH_SALTGPG" -O "$gpgblob" || return 1
 	fi
 
 	# Deploy GPG keys
-	# NOTE: gpg option order is very important
-	if [ -f "$TH_SALTPWF" ]; then
-		gpg --batch --passphrase-file "$TH_SALTPWF" --decrypt "$gpgblob" | \
-			tar -xC /etc/salt/ || (rm "$gpgblob"; return 1)
-	else
-		gpg --batch --decrypt "$gpgblob" | \
-			tar -xC /etc/salt/ || (rm "$gpgblob"; return 1)
-	fi
+	mkdir "$keydir"; chmod 0700 "$keydir"
+	unset pwfile; [[ -f "$TH_SALTPWF" ]] && pwfile=('--passphrase-file' "$TH_SALTPWF")
+	gpg --batch "${pwfile[@]}" --decrypt "$gpgblob" | gpg --homedir "$keydir" --import
+
+	# Verification
+	gpg --homedir "$keydir" --list-secret-keys | grep -q 'salt' ||
+		die 'Could not verify gpg keys were installed correctly'
+
+	# Cleanup (leave broken for investigation)
 	rm "$gpgblob"
-	chown -R root:root /etc/salt/
 }
 
 
 ##
 # Copied from https://github.com/MTecknology/script-helpers
 ##
+
+# Log Levels
+DEBUG=0; INFO=1; WARN=2; ERROR=3
+readonly DEBUG INFO WARN ERROR
+export DEBUG INFO WARN ERROR
 
 # Check if a command (or alias/function) is available.
 # Usage: command_present bin
@@ -204,6 +244,21 @@ _lock_acquire() {
 	echo $$ > "$1"
 
 	return 0
+}
+
+# Print a formatted message if env[LOG_LEVEL] >= level.
+log() {
+	if [ "${LOG_LEVEL:-2}" -le "$1" ]; then
+		case "$1" in
+			(0) _lvl='DEBUG';;
+			(1) _lvl='INFO';;
+			(2) _lvl='WARN';;
+			(3) _lvl='ERROR';;
+			(*) _lvl='UNKNOWN';;
+		esac
+
+		printf '*** %s: %s ***\n' "$_lvl" "$2"
+	fi
 }
 
 
diff --git a/iso/build_iso b/iso/build_iso
--- a/iso/build_iso
+++ b/iso/build_iso
@@ -32,20 +32,24 @@ parse_options() {
 	export TH_SRC="${TH_SRC:-./debian-netinst.iso}"
 	export TH_DST="${TH_DST:-./teckhost.iso}"
 	export TH_SEED="${TH_SEED:-preseed.cfg}"
-	export TH_GRUB="${TH_GRUB:-./auto-grub.cfg}"
+	export TH_GRUBb="${TH_GRUBb:-./grub-bios.cfg}"
+	export TH_GRUBe="${TH_GRUBe:-./grub-efi.cfg}"
+	export THT_GRUBTEST="${THT_GRUBTEST:-TEMPLATE_METHOD=lvm BS_pillar_root=test/pillar TH_SALTGPG=https://raw.githubusercontent.com/MTecknology/teckhost/master/test/pillar/skeys.gpg}"
 	export TH_KEEP="${TH_KEEP:-False}"
 	export THT_DEVICE="${THT_DEVICE:-/dev/nvme0n1}"
 	export LOG_LEVEL="${LOG_LEVEL:-1}"
 
-	while getopts 'c:i:o:s:g:kd:l:h' OPT; do
+	while getopts 'c:i:o:s:f:g:kd:b:l:h' OPT; do
 		case "$OPT" in
 			c) TH_CKSUM="$OPTARG";;
 			i) TH_SRC="$OPTARG";;
 			o) TH_DST="$OPTARG";;
 			s) TH_SEED="$OPTARG";;
-			g) TH_GRUB="$OPTARG";;
+			f) TH_GRUBb="$OPTARG";;
+			g) TH_GRUBe="$OPTARG";;
 			k) TH_KEEP=True;;
 			d) THT_DEVICE="$OPTARG";;
+			b) THT_GRUBTEST="$OPTARG";;
 			l) LOG_LEVEL="$OPTARG";;
 			h) show_help; exit 1;;
 			*) die "Unexpected argument provided: '$OPT'";;
@@ -66,8 +70,10 @@ show_help() {
 	  -i X${t}Pristine ISO to be modified (can be http)
 	  -o X${t}Output ISO
 	  -s X${t}Preseed template to embed into ISO
-	  -g X${t}Grub configuration file
+	  -f X${t}Grub (bios) configuration file
+	  -g X${t}Grub (efi) configuration file
 	  -d X${t}Installation device
+	  -b X${t}Options added to test entry in grub boot menu
 	  -l X${t}Log level (0=Debug, 1=Info, 2=Warn, 3=Error)
 	  -k${t}Keep temporary directory
 	  -h${t}Print this help text and exit
@@ -77,9 +83,11 @@ show_help() {
 	  TH_SRC${t}./debian-netinst.iso
 	  TH_DST${t}./teckhost.iso
 	  TH_SEED${t}./preseed.cfg
-	  TH_GRUB${t}./auto-grub.cfg
+	  TH_GRUBb${t}./grub-bios.cfg
+	  TH_GRUBe${t}./grub-efi.cfg
 	  TH_KEEP${t}True
 	  THT_DEVICE${t}/dev/nvme0n1
+	  THT_GRUBTEST${t}TEMPLATE_METHOD=lvm BS_pillar_root=test/pillar TH_SALTGPG=https://raw.githubusercontent.com/MTecknology/teckhost/master/test/pillar/skeys.gpg
 	  LOG_LEVEL${t}1  (info)
 
 	Tell build_iso to pull a remote iso and store in /tmp/\$TH_CKSUM.iso:
@@ -100,7 +108,7 @@ safety_checks() {
 
 	# Verify provided values point at files
 	[ -f "$TH_SEED" ] || die 'Seed file not found'
-	[ -f "$TH_GRUB" ] || die 'Grub configuration not found'
+	[ -f "$TH_GRUBe" ] || die 'Grub v2 configuration not found'
 
 	# Other option checks
 	is_int "$LOG_LEVEL" || die 'Log level must be an integer (0-3)'
@@ -152,17 +160,17 @@ _get_websource() {
 # Insert an auto-only grub boot config
 inject_grubconfig() {
 	log "$DEBUG" 'Copying grub config'
-	cp "$TH_GRUB" "$TH_TEMP/boot/grub/grub.cfg"
+
+	# Copy template and update template value(s)
+	sed -e "s|TEMPLATE_GRUBTEST|$THT_GRUBTEST|" "$TH_GRUBb" >"$TH_TEMP/isolinux/menu.cfg"
+	sed -e "s|TEMPLATE_GRUBTEST|$THT_GRUBTEST|" "$TH_GRUBe" >"$TH_TEMP/boot/grub/grub.cfg"
 }
 
 # Inject a custom preseed into initrd
 inject_preseed() {
-	# Copy template and update template value(s)
 	log "$DEBUG" 'Generating preseed file'
+	# Copy template and update template value(s)
 	sed -e "s|TEMPLATE_DEVICE|$THT_DEVICE|" "$TH_SEED" > "$TH_TEMP/preseed.cfg"
-		# This was "replaced" because of issues with multi-preseed options.
-		# See preseed.cfg header for more information.
-		#-e "s|TEMPLATE_METHOD|$THT_METHOD|" \
 
 	# Not the cleanest assumption, but we error if files are missisg
 	basedir="$(dirname "$0")/../"
diff --git a/test/vbox_create b/test/vbox_create
--- a/test/vbox_create
+++ b/test/vbox_create
@@ -10,7 +10,7 @@ main() {
 
 	# Prep
 	safety_checks
-	lock acquire "$0" || die 'Unable to acquire lock'
+	lock acquire "$0$TH_VMNAME" || die 'Unable to acquire lock'
 
 	# Flight
 	destroy_vm
@@ -32,29 +32,32 @@ show_usage() {
 	  -i [path]${t}Location of installer ISO
 	  -n [name]${t}Name of VM
 	  -s [path]${t}Path to use for screenshots
+	  -b [type]${t}Boot type (efi*|bios)
 	  -h${t}${t}Print this help text
 
 	Defaults (Environment Variables):
 	  TH_ISOPATH${t}./teckhost.iso
 	  TH_VMNAME${t}testpc1
 	  TH_SHOTS${t}""
+	  TH_BOOT${t}efi
 	EOF
 }
 
 # Parse options, prioritizing args > env > defaults
-# Exports: TH_SALTGPG
 parse_options() {
 	# Default values
 	export TH_ISOPATH="${TH_ISOPATH:-./teckhost.iso}"
 	export TH_VMNAME="${TH_VMNAME:-testpc1}"
 	export TH_SHOTS="${TH_SHOTS}"
+	export TH_BOOT="${TH_BOOT:-efi}"
 
 	# Modify defaults
-	while getopts 'i:n:s:h' opt; do
+	while getopts 'i:n:s:b:h' opt; do
 		case "$opt" in
 			(i) TH_ISOPATH="$OPTARG";;
 			(n) TH_VMNAME="$OPTARG";;
 			(s) TH_SHOTS="$OPTARG";;
+			(b) TH_BOOT="$OPTARG";;
 			(h) show_usage; exit 0;;
 			(*) die "Invalid option: $opt"
 		esac
@@ -79,7 +82,9 @@ create_vm() {
 	VBoxManage modifyvm "$TH_VMNAME" --ioapic on
 	VBoxManage modifyvm "$TH_VMNAME" --cpus 4
 	VBoxManage modifyvm "$TH_VMNAME" --memory 1024 --vram 128
-	VBoxManage modifyvm "$TH_VMNAME" --firmware efi || return 1
+	if [[ "$TH_BOOT" = 'efi' ]]; then
+		VBoxManage modifyvm "$TH_VMNAME" --firmware efi || return 1
+	fi
 
 	# Networking
 	VBoxManage modifyvm "$TH_VMNAME" --nic1 nat
@@ -105,6 +110,10 @@ install_os() {
 
 	# Press "t" for testing install (see --hotkey=t in iso/auto-grub.cfg)
 	VBoxManage controlvm "$TH_VMNAME" keyboardputstring "t" || return 1
+	if [[ "$TH_BOOT" = 'bios' ]]; then
+		# BIOS mode requires pressing enter
+		VBoxManage controlvm "$TH_VMNAME" keyboardputscancode 1C 9C
+	fi
 
 	# Local testing took approximately 17 minutes
 	printf 'Waiting (up to 30 minutes) for install to finish ...'
@@ -114,7 +123,7 @@ install_os() {
 		if [[ "$TH_SHOTS" ]]; then
 			VBoxManage controlvm "$TH_VMNAME" screenshotpng "$TH_SHOTS-$i.png"
 			# Switch to TTY4 around preseed invokation
-			VBoxManage controlvm "$TH_VMNAME" keyboardputscancode 1D 38 3E BE B8 9D
+			[ "$i" = 18 ] && VBoxManage controlvm "$TH_VMNAME" keyboardputscancode 1D 38 3E BE B8 9D
 		fi
 		sleep 10; printf '.'
 		# The installer iso will remain mounted until the installer triggers an eject.
@@ -124,7 +133,7 @@ install_os() {
 		# Return to TTY1 and take final screenshot
 		VBoxManage controlvm "$TH_VMNAME" keyboardputscancode 1D 38 3B BB B8 9D
 		VBoxManage controlvm "$TH_VMNAME" screenshotpng "$TH_SHOTS-final.png"
-		tar -czf "$TH_SHOTS.tgz" "$TH_SHOTS"-*.png
+		tar -cf "$TH_SHOTS.tar" "$TH_SHOTS"-*.png
 	fi
 	printf 'Done\n'
 
